### ISSUE TITLE
project doesn't build anymore against latest go tools

### ISSUE THREAD

**Issue by gadumitrachioaiei** [clipperhouse/typewriter#11]
# github.com/clipperhouse/typewriter
..\typewriter\package.go:94: not enough arguments in call to types.Eval

Eval seems to have changed:
https://github.com/golang/tools/commit/665374f1c86631cf73f4729095d4cf4313670545#diff-6df9913cf1f49500f1a1d627f6c448ea

**Comment by clipperhouse** [comment]
Latest commit should fix it. You’ll want to `go get -u` across the board. Thanks and let me know how it goes. @gadumitrachioaiei @rzab

**Comment by rzab** [comment]
Yep, all good for me, thank you.

**Comment by gadumitrachioaiei** [comment]
Thanks!
