### ISSUE TITLE
Splitting the project

### ISSUE THREAD

**Issue by tarqe39** [clipperhouse/typewriter#2]
Hi, 
first of all typewriter is a great idea and nice job realizing that idea. Was wondering would it be possible to split the project up so the annotation parsing is separated from typewriter. 
I have a feeling that it could be more generalized. For instance for scaffolding a web project. Lets say you annotate a model and call an external app to scaffold repository for the model. Or write your view model and scaffold a controller. Possibilities are great, especially with code that has a lot boilerplate.

Does it make any sense? I looked into current implementation and its more oriented on fluent linq-like api and it would be hard to use in scenarios suggested (or am I wrong? :))

**Comment by clipperhouse** [comment]
The idea is to make the parser a separate package? We could do that but I don’t see it as very interesting. The current implementation is fairly tightly coupled to the (e.g.) the `Tag` and `Type` types. It could be decoupled, but it doesn’t buy much for the needs of gen. Feel free to fork it, though.
