### ISSUE TITLE
Want information about "struct fields" from typewriter.Type

### ISSUE THREAD

**Issue by reiver** [clipperhouse/typewriter#5]
When someone creates a typewriter to work with gen, their code will have a method with the signature:
```
Write(w io.Writer, t typewriter.Type) error
```

The `t` variable, of type `typewriter.Type`, tells the typewriter information about the type being acted on.

Sometimes this type is a struct.

In the case where the type is a struct, if would be nice if the `typewriter.Type` parameter would provide information about the (public) fields of the struct.

**Comment by clipperhouse** [comment]
Makes sense.

This will likely take the form of embedding a [types.Type](https://godoc.org/golang.org/x/tools/go/types#Type) into `typewriter.Type`. One can type-switch on that and extract the full gamut of information, eg [types.Struct](https://godoc.org/golang.org/x/tools/go/types#Struct).

**Comment by clipperhouse** [comment]
I’ve implemented this here: https://github.com/clipperhouse/typewriter/commit/1300d9914f29af3869b13edee17c0450297df982

Have a look at the test [here](https://github.com/clipperhouse/typewriter/blob/master/package_test.go#L44). You can cast typewriter.Type into [*types.Struct](https://godoc.org/golang.org/x/tools/go/types#Struct), which in turn exposes the members of the struct.
